version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app/server
    volumes:
      - ./server:/app/server
    environment:
      - SERVER_IP=0.0.0.0 
      - SERVER_PORT=5001
      - DISPLAY=:0 
    command: ["python", "server_gui.py"]  

  client:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app/client
    volumes:
      - ./client:/app/client
    depends_on:
      - server 
    environment:
      - SERVER_IP=server
      - SERVER_PORT=5001
      - DISPLAY=:0 
    command: ["python", "client_gui.py"] 
